name: CI/CD & Security

permissions:
  contents: read

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  build-and-check:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/valerok/trello-mcp-server:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv (if available)
        run: |
          pip install uv || true

      - name: Install dependencies
        run: |
          if command -v uv > /dev/null; then
            uv pip install -r requirements.txt || uv pip install . || true
          else
            pip install -r requirements.txt || pip install .
          fi

      - name: Lint with ruff (if available, fallback to flake8)
        run: |
          pip install ruff flake8 || true
          if command -v ruff > /dev/null; then
            ruff check .
          else
            flake8 .
          fi

      - name: Run Bandit security checks
        run: |
          pip install bandit
          bandit -r server/ || bandit -r .

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to Docker Hub
        if: github.ref == 'refs/heads/master'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image with cache
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max

      - name: Show IMAGE_NAME
        run: echo $IMAGE_NAME

      - name: List Docker images
        run: docker images

      - name: Install Grype
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Scan Docker image for vulnerabilities (Grype)
        run: |
          grype $IMAGE_NAME --fail-on high
        continue-on-error: true

      - name: Show success message
        if: success()
        run: echo "All checks passed!" 